package sisinfo;
import java.sql.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.sql.Date;
import java.sql.DriverManager;

import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


import com.sun.media.sound.ModelOscillator;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author VMVZ
 */
public class NewJFrame extends javax.swing.JFrame {
    
Connection conex;
       String nombre="";



    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() throws ClassNotFoundException  {
       initComponents();
       
    }

    public void setConex(com.mysql.jdbc.Connection aux){
    
        conex = aux;
    }
    
    private void cargar(){
    
        DefaultTableModel modelo = new DefaultTableModel();
        try {
          
           jT.setModel(modelo);
           PreparedStatement ps=null;
           ResultSet rs=null;
           
           
           String sql="SELECT nombreMed,cant,precio FROM medicamento m,compra c where m.idMedicamento = c.Medicamento_idMedicamento";  
           ps=(PreparedStatement) conex.prepareStatement(sql);
           rs=ps.executeQuery();
           
           ResultSetMetaData rsMd=rs.getMetaData();
           int cantidadColumnas=rsMd.getColumnCount();
           
           modelo.addColumn("nombre");
           modelo.addColumn("cantidad");
           modelo.addColumn("precio");
           while(rs.next()){
               Object[] filas =new Object[cantidadColumnas];
               for (int i = 0; i < cantidadColumnas; i++) {
                    filas[i]=rs.getObject(i+1);
               }
              modelo.addRow(filas);  
           }  
        } catch (Exception e) {
                System.out.println("error");
        }     
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btninsertar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT = new javax.swing.JTable();
        btneliminar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 51, 255));
        jLabel2.setText("desea modificar algo?");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 360, 70));

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 50)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 102));
        jLabel3.setText("BIENVENIDO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 310, 60));

        btninsertar.setBackground(new java.awt.Color(0, 204, 153));
        btninsertar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btninsertar.setForeground(new java.awt.Color(255, 0, 51));
        btninsertar.setText("AÑADIR");
        btninsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninsertarActionPerformed(evt);
            }
        });
        getContentPane().add(btninsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 560, 180, 40));

        jT.setForeground(new java.awt.Color(255, 255, 0));
        jT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "nombre", "cantidad", "precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jT);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 780, 140));

        btneliminar.setBackground(new java.awt.Color(0, 153, 102));
        btneliminar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btneliminar.setForeground(new java.awt.Color(204, 0, 51));
        btneliminar.setText("ELIMINAR");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 560, 190, 40));

        jButton3.setBackground(new java.awt.Color(0, 204, 102));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(204, 0, 51));
        jButton3.setText("CARGAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 560, 160, 40));

        jButton4.setBackground(new java.awt.Color(255, 51, 51));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(204, 204, 0));
        jButton4.setText("BUSCAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, -1, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("nombre:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));
        getContentPane().add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 300, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/73679594-detalles-de-farmacia-farmacia-rubia-sexy-farmacéutico-buscando-antibióticos-en-la-computadora-portátil.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 1140, 740));

        pack();
    }// </editor-fold>                        

    
 
    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
         com.mysql.jdbc.PreparedStatement ps=null;
         DefaultTableModel modelo = new DefaultTableModel();
        try {
          
            
            int fila=jT.getSelectedRow();
            String codigo=jT.getValueAt(fila, 0).toString();
            
            ps=(com.mysql.jdbc.PreparedStatement) conex.prepareStatement("DELETE FROM medicamento WHERE nombreMed = ?");
            ps.setString(1,codigo);
            ps.execute();
            modelo.removeRow(fila);
        } catch (Exception e) {
        }

    }                                           

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        String codigo=txtnombre.getText();
       
        
        String where ="";
        if(!"".equals(codigo)){
            if(!"".equals(nombre)){
                where=" WHERE nombreMed = '"+ nombre+"'";
            }
        }
        
         try {
           DefaultTableModel modelo=new DefaultTableModel();
           jT.setModel(modelo);
           PreparedStatement ps=null;
           ResultSet rs=null;
           
           String sql="SELECT nombreMed,cant,precio FROM medicamento m,compra c where m.idMedicamento = c.Medicamento_idMedicamento"+where;  
             System.out.println(sql);
           ps=(PreparedStatement) conex.prepareStatement(sql);
           rs=ps.executeQuery();
           
           ResultSetMetaData rsMd=rs.getMetaData();
           int cantidadColumnas=rsMd.getColumnCount();
           
           modelo.addColumn("nombre");
           modelo.addColumn("canitdad");
           modelo.addColumn("precio");
           while(rs.next()){
               Object[] filas =new Object[cantidadColumnas];
               for (int i = 0; i < cantidadColumnas; i++) {
                    filas[i]=rs.getObject(i+1);
               }
              modelo.addRow(filas);  
           }  
        } catch (Exception e) {
                System.out.println("error");
        }
    }                                        

    private void btninsertarActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        RegistroDeMedicamentosDeProveedor aux = new RegistroDeMedicamentosDeProveedor();
        aux.setConex(conex);
        aux.setVisible(true);
    }                                           

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        cargar();
    }                                        
private void limpiar() {
        txtnombre.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new NewJFrame().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btninsertar;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jT;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration                   
}
